version: '3.9'
services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/code
    environment:
      - FLASK_DEBUG=true
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
