version: '3'
services:
  web:
    build: .
    image: mongo:latest
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      - FLASK_DEBUG=true
  redis:
    image: "redis:alpine"
